"""empty message

Revision ID: 000b6a5a244f
Revises: 9cefbc2358d0
Create Date: 2024-01-10 03:09:27.753790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '000b6a5a244f'
down_revision = '9cefbc2358d0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
